### ISSUE TITLE
Suggestion: Update README w/ instructions for running

### ISSUE THREAD

**Issue by ajpierce** [peterjpierce/project_euler#1]
Earlier today, I attempted to clone the repository and run some of the solutions on my laptop, but I ran into the following problems:

## Problem 1: Python Version
The first set of errors I ran into were a result of me trying to execute the files with Python 2.7.  I got a little further when I executed the file with `python3`

**Suggestion:** Indicate in the README that the user should use python3 to execute the files

## Problem 2: Imports
When attempting to execute a solution, I ran into the following error:

```
$ python3 solutions/027.py 
Traceback (most recent call last):
  File "solutions/027.py", line 26, in <module>
    from shared import util
ImportError: No module named 'shared'
```

I noticed that there are no `__init__.py` files checked in to the repo.  Should these be checked in, or is there some trick to running in a Virtualenv that I should know?

Thanks for your hard work!

**Comment by peterjpierce** [comment]
Thank you @ajpierce  for the good suggestion.  Please see the [new](https://github.com/peterjpierce/project_euler/commit/eb0185cec9067153536152409ae725c8c64bde1b) README and run utility!
